function [] = KML2html (filename, str, launch_phi, launch_lambda, launch_h)
% KML2HTML KMLファイルからPCのブラウザで表示可能なようにHTMLファイルを出力
% Google Earth APIを使用して、HTMLの<head>要素の中に
% API呼び出しのjavascriptを記述。入力のKMLファイルの中身はperceKml関数を使用
% Earth APIにおけるKMLの使用法にはKmlNetworkLink, fetchKml, perceKml
% があるが、前者２つはパブリックな場所にKMLファイルを置かないと
% 読み込んでくれないので、perceKmlを使用する。
% @param filename 出力するHTMLファイル名(string)
% @param str 必要なKMLファイル
% @param launch_phi, launch_lambda, launch_h 射点の緯度経度高度[deg][deg][m]

fileaddress = strcat('output/',filename,'.html');
[fid, msg] = fopen(fileaddress, 'w');

string1 = ['<html>\n'...
			'<head>\n'...
			'\t<title>Flight Simulation</title>\n'...
			'\t<script type="text/javascript" src="https://www.google.com/jsapi"> </script>\n'...
			'\t<script type="text/javascript">\n'...
			'\t\tvar ge;\n'...
			'\t\tvar placemark;\n'...
			'\t\tvar object;\n'...
			'\t\tgoogle.load("earth", "1", {"other_params":"sensor=false"});\n'...
			'\t\tfunction init() {\n'...
			'\t\t\tgoogle.earth.createInstance(''map3d'', initCB, failureCB);\n'...
			'\t\t}\n'...
			'\t\tfunction initCB(instance) {\n'...
			'\t\t\tge = instance;\n'...
			'\t\t\tge.getWindow().setVisibility(true);\n'...
         	'\t\t\tvar kmlString = '''];

% ---- KMLファイルの書き出し ----
% 行ごとに''で囲うのと、+演算子で結合する必要がある。
new_str = strrep(str, '\n', '''\n\t\t+ ''');
string2 = new_str;


string3 = [''';\n'...
			'\t\tvar kmlObject = ge.parseKml(kmlString);\n'...
        	'\t\tge.getFeatures().appendChild(kmlObject);\n'...
        	'\t\tvar la = ge.createLookAt('''');\n'...
			'\t\tla.set('];

% ---- 初期カメラの位置指定 ----
string4 = strcat(num2str(launch_phi), ', ', num2str(launch_lambda), ',',...
				num2str(launch_h));

% KmlLookAt.set関数は
% (latitude、longitude、altitude、altitudeMode、heading、tilt、range)
string5 = [', ge.ALTITUDE_RELATIVE_TO_GROUND, 0, 45, 2000);\n'...
			'\t\tge.getView().setAbstractView(la);\n'...
			'\t}\n'...
			'\tfunction failureCB(errorCode) {\n'...
			'\t}\n'...
			'\tgoogle.setOnLoadCallback(init);\n'...
			'\t</script>\n'...
			'</head>\n'...
			'<body>\n'...
			'\t<div id="map3d" style="height:600px; width:800px;"></div>\n'...
			'</body>\n'...
			'</html>'];
string = strcat(string1, string2, string3, string4, string5);

fprintf(fid, string);
fclose(fid);