function [] = KML2html (filename, str, launch_phi, launch_lambda, launch_h)

fileaddress = strcat('output/',filename,'.html');
[fid, msg] = fopen(fileaddress, 'w');

string1 = ['<html>\n'...
			'<head>\n'...
			'\t<title>parsekml_example.html</title>\n'...
			'\t<script type="text/javascript" src="https://www.google.com/jsapi"> </script>\n'...
			'\t<script type="text/javascript">\n'...
			'\t\tvar ge;\n'...
			'\t\tvar placemark;\n'...
			'\t\tvar object;\n'...
			'\t\tgoogle.load("earth", "1", {"other_params":"sensor=false"});\n'...
			'\t\tfunction init() {\n'...
			'\t\t\tgoogle.earth.createInstance(''map3d'', initCB, failureCB);\n'...
			'\t\t}\n'...
			'\t\tfunction initCB(instance) {\n'...
			'\t\t\tge = instance;\n'...
			'\t\t\tge.getWindow().setVisibility(true);\n'...
         	'\t\t\tvar kmlString = '''];

new_str = strrep(str, '\n', '''\n\t\t+ ''');
string2 = new_str;


string3 = [''';\n'...
			'\t\tvar kmlObject = ge.parseKml(kmlString);\n'...
        	'\t\tge.getFeatures().appendChild(kmlObject);\n'...
        	'\t\tvar la = ge.createLookAt('''');\n'...
			'\t\tla.set('];
string4 = strcat(num2str(launch_phi), ', ', num2str(launch_lambda), ',',...
				num2str(launch_h));
string5 = [', ge.ALTITUDE_RELATIVE_TO_GROUND, 0, 45, 2000);\n'...
			'\t\tge.getView().setAbstractView(la);\n'...
			'\t}\n'...
			'\tfunction failureCB(errorCode) {\n'...
			'\t}\n'...
			'\tgoogle.setOnLoadCallback(init);\n'...
			'\t</script>\n'...
			'</head>\n'...
			'<body>\n'...
			'\t<div id="map3d" style="height:400px; width:600px;"></div>\n'...
			'</body>\n'...
			'</html>'];
string = strcat(string1, string2, string3, string4, string5);

fprintf(fid, string);
fclose(fid);