function str = pos2KML( filename, u, e, n, xr, yr, zr )

fileaddress = strcat('output/',filename,'.kml');
[fid, msg] = fopen(fileaddress, 'w');

string1 = ['<?xml version="1.0" encoding="UTF-8"?>\n'...
	'<kml xmlns="http://www.opengis.net/kml/2.2"> <Document>\n'...
	'\t<name>Flight Paths</name>\n'...
	'\t<description>Rocket Flight Paths.</description>\n'...
	'\t<Style id="yellowLineGreenPoly">\n'...
	'\t<LineStyle>\n'...
	'\t\t<color>7f00ffff</color>\n'...
	'\t\t<width>4</width>\n'...
	'\t</LineStyle>\n'...
	'\t<PolyStyle>\n'...
	'\t\t<color>7f00ff00</color>\n'...
	'\t</PolyStyle>\n'...
	'\t</Style>\n'...
	'\t<Placemark>\n'...
	'\t\t<name>Absolute Extruded</name>\n'...
	'\t\t<description>Transparent green wall with yellow outlines</description>\n'...
	'\t\t<styleUrl>#yellowLineGreenPoly</styleUrl>\n'...
	'\t\t<LineString>\n'...
	'\t\t\t<extrude>1</extrude>\n'...
	'\t\t\t<tessellate>1</tessellate>\n'...
	'\t\t\t<altitudeMode>absolute</altitudeMode>\n'...
	'\t\t\t<coordinates>\n'];
fprintf(fid, string1);

[ecef_x, ecef_y, ecef_z] = launch2ecef(u, e, n, xr, yr, zr);
[phi, lambda, h] = ecef2blh(ecef_x, ecef_y, ecef_z);
string2 = '';
for i = 1:length(phi)
	string = sprintf('\t\t\t%.6f,%.6f,%.2f', lambda(i), phi(i), h(i));
	string2 = strcat(string2, string, '\n');
end
fprintf(fid, string2);
string3 = ['\t\t\t</coordinates>\n'...
	'\t</LineString> </Placemark>\n'...
	'</Document> </kml>'];
fprintf(fid, string3);

str = strcat(string1, string2, string3);