% ---- パラメータ設定 ----
% m0: 初期質量[kg]
% Isp: 比推力[sec]
% g0: 地上での重力加速度[m/s2]
% FT: 推力[N]
% Tend: 燃焼時間[sec]
% At: スロート径[m2]
% Area: 機体の断面積[m2]
% CLa: 揚力傾斜[/rad]
% CD: 抗力係数[-]
% length_GCM: エンジンピボット点からの重心位置ベクトル[m](3x1)
% length_A: エンジンピボット点からの空力中心点位置ベクトル[m] (3x1)
% IXX,IYY,IZZ: 慣性モーメント[kgm2]
% IXXdot,IYYdot,IZZdot: 慣性モーメントの時間変化[kgm2/sec]
% azimth, elevation: 初期姿勢の方位角、仰角[deg]
% VWH:　水平座標系においての風速(Up-East-North) [m/s] (3x1)
ROCKET = struct( ...
'mf', 88.0, ...
'm0', 400.0, ...
'Isp', 200, ...
'g0', 9.80665, ...
'FT', [7500], ...
'Tend', [70], ...
'At', 0.01, ...
'Area', 0.120, ...
'CLa', 1.5, ... %3.5
'length_GCM', [-1.00; 0; 0], ...
'length_A', [-0.010; 0; 0], ...
'Ijj', [10; 50; 50], ...
'IXXdot', 0, ...
'IYYdot', 0, ...
'IZZdot', 0, ...
'azimth', 45, ...
'elevation', 85 ...
);